# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e33d3f5a-a192-45f9-8360-b3e047fffaa3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6c697203-56ce-42ac-b9ab-1b4caf238307".device = "/dev/disk/by-uuid/6c697203-56ce-42ac-b9ab-1b4caf238307";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/939E-1B0C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/086b2389-7cb1-4d1f-98c0-651b21dd8d43"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
