{ pkgs, config, ... }:

let
  _changeWallpaper = pkgs.pkgs.writeShellScriptBin "_changewp" ''
    awww img --resize=crop "$1"
  '';

  _wallpaperLocation = config.home.homeDirectory + "/Pictures/Wallpapers/";

  shuffleWallpaper = pkgs.pkgs.writeShellScriptBin "shufflewallpaper" ''
    ${_changeWallpaper}/bin/_changewp "$(find ${_wallpaperLocation} -type f | shuf -n 1 | xargs)"
  '';

  pickWallpaper = pkgs.stdenv.mkDerivation {
    name = "pickwallpaper";

    # We are generating the script on the fly, so no source needed
    unpackPhase = "true";

    nativeBuildInputs = [ pkgs.installShellFiles ];

    installPhase = ''
      mkdir -p $out/bin

      # Write the script
      cat <<EOF > $out/bin/pickwallpaper
      #!/usr/bin/env bash
      if [ -z "\$1" ]; then
        # List only the filenames (not absolute paths) for easier selection
        find ${_wallpaperLocation} -maxdepth 1 -type f -printf "%f\n"
        exit
      fi

      targetWp="\$1"
      ${_changeWallpaper}/bin/_changewp "${_wallpaperLocation}\$targetWp"
      EOF

      chmod +x $out/bin/pickwallpaper

      # Generate and install the Bash completion
      installShellCompletion --cmd pickwallpaper \
      --zsh <(cat <<EOF
          #compdef pickwallpaper
          _pickwallpaper() {
            local -a wallpapers
            # Generate list of files from the wallpaper directory
            wallpapers=(\$(ls -1 "${_wallpaperLocation}" 2>/dev/null))
            _describe 'wallpapers' wallpapers
          }
          _pickwallpaper "\$@"
      EOF
      )
    '';
  };

  generateLockAscii-src = builtins.readFile ./scripts/generateLockAscii.sh;
  generateLockAscii =
    (pkgs.pkgs.writeShellScriptBin "generateLockAscii" generateLockAscii-src).overrideAttrs
      (old: {
        buildCommand = "${old.buildCommand}\n patchShebangs $out";
      });

  mon-mirror = pkgs.pkgs.writeShellScriptBin "mon-mirror" ''
    if [ -z "$1" ]; then
      hyprctl monitors | grep -A1 "^Monitor"
      exit
    fi

    targetMonitor="$1"
    sourceMonitorOrDefault="$2"

    if [ -z "$sourceMonitorOrDefault" ]; then
      hyprctl keyword monitor $targetMonitor,preferred,auto,auto
    elif [ "$sourceMonitorOrDefault" = "y" ]; then
      hyprctl keyword monitor $targetMonitor,preferred,auto,auto,mirror,eDP-1
    else
      hyprctl keyword monitor $targetMonitor,preferred,auto,auto,mirror,$sourceMonitorOrDefault
    fi
  '';

  startScript = pkgs.pkgs.writeShellScriptBin "start" ''
    awww-daemon &
    ${shuffleWallpaper}/bin/shufflewallpaper &

    hyprctl setcursor Hackneyed 24 &

    nm-applet --indicator &

    waybar &

    dunst &

    copyq --start-server
  '';
in
{
  home.packages = [
    mon-mirror
    shuffleWallpaper
    pickWallpaper
  ];

  programs.hyprlock = {
    enable = true;
    settings = {
      general = {
        disable_loading_bar = true;
        grace = 3;
        hide_cursor = true;
        no_fade_in = false;
      };

      auth = {
        fingerprint.enabled = true;
      };

      background = [
        {
          path = "screenshot";
          blur_passes = 3;
          blur_size = 8;
        }
      ];

      label = [
        {
          color = "rgb(193, 0, 7)";
          font_family = "monospace";
          font_size = 12;

          position = "0, 150";

          text = "cmd[once] ${generateLockAscii}/bin/generateLockAscii";
        }
      ];

      shape = [
        {
          size = "100%, 200";
          position = "0, 150";
          rounding = 0;

          color = "rgba(70, 8, 9, 0.7)";

          border_size = 1;
          border_color = "rgb(193, 0, 7)";

          zindex = -1;
        }
      ];

      input-field = [
        {
          size = "200, 50";
          position = "0, 0";
          rounding = 0;
          monitor = "";
          dots_center = true;
          dots_text_format = "*";
          fade_on_empty = false;

          font_family = "monospace";

          font_color = "rgb(193, 0, 7)";
          inner_color = "rgb(70, 8, 9)";
          outer_color = "rgb(193, 0, 7)";
          check_color = "rgb(193, 0, 7)";
          fail_color = "rgb(193, 0, 7)";

          outline_thickness = 1;
          placeholder_text = "Enter Passphrase";
          shadow_passes = 2;
        }
      ];
    };
  };

  wayland.windowManager.hyprland = {
    enable = true;
    configType = "lua";

    extraConfig = ''
      -- Generated by Home Manager; this file uses Hyprland's Lua API.
      local terminal = "kitty"
      local fileManager = "nautilus --new-window"
      local menu = "rofi -show"
      local lock = "hyprlock"
      local mainMod = "SUPER"
      local hyprshotConf = "--freeze --output-folder ~/Pictures/Screenshots"
      local hyprshotOpen = "-- loupe"

      hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = "auto" })
      hl.monitor({ output = "DP-3", mode = "preferred", position = "auto-left", scale = "auto" })
      hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

      -- Keep the generated HyprDynamicMonitors configuration active.
      hl.exec_cmd("hyprctl keyword source ~/.config/hypr/monitors.conf")

      hl.env("XCURSOR_SIZE", "24")
      hl.env("HYPRCURSOR_SIZE", "24")

      hl.config({
        general = {
          gaps_in = 5,
          gaps_out = 10,
          border_size = 1,
          col = {
            active_border = { colors = { "rgba(dc2626dd)", "rgba(dc2626dd)" }, angle = 45 },
            inactive_border = "rgba(450a0aff)",
          },
          resize_on_border = true,
          hover_icon_on_border = true,
          allow_tearing = false,
          layout = "dwindle",
        },
        decoration = {
          rounding = 0,
          rounding_power = 2,
          active_opacity = 1.0,
          inactive_opacity = 0.9,
          blur = { enabled = true, size = 5, passes = 2, vibrancy = 0.1696 },
        },
        animations = { enabled = true },
        dwindle = { preserve_split = true },
        master = { new_status = "master" },
        misc = {
          force_default_wallpaper = 0,
          disable_hyprland_logo = true,
          disable_splash_rendering = true,
          animate_manual_resizes = true,
          vrr = 2,
        },
        debug = { vfr = true },
        input = {
          kb_layout = "us",
          kb_variant = "",
          kb_model = "",
          kb_options = "caps:ctrl_modifier,caps:nocaps",
          kb_rules = "",
          follow_mouse = 1,
          sensitivity = 0,
          touchpad = {
            natural_scroll = false,
            disable_while_typing = false,
            tap_to_click = true,
            drag_lock = true,
            scroll_factor = 0.5,
          },
        },
      })

      hl.curve("easeoutquint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
      hl.curve("easeinoutcubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
      hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
      hl.curve("almostlinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
      hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

      local animations = {
        { leaf = "global", speed = 10, bezier = "default" },
        { leaf = "border", speed = 5.39, bezier = "easeoutquint" },
        { leaf = "windows", speed = 4.79, bezier = "easeoutquint" },
        { leaf = "windowsIn", speed = 4.1, bezier = "easeoutquint", style = "popin 87%" },
        { leaf = "windowsOut", speed = 1.49, bezier = "linear", style = "popin 87%" },
        { leaf = "fadeIn", speed = 1.73, bezier = "almostlinear" },
        { leaf = "fadeOut", speed = 1.46, bezier = "almostlinear" },
        { leaf = "fade", speed = 3.03, bezier = "quick" },
        { leaf = "layers", speed = 3.81, bezier = "easeoutquint" },
        { leaf = "layersIn", speed = 4, bezier = "easeoutquint", style = "fade" },
        { leaf = "layersOut", speed = 1.5, bezier = "linear", style = "fade" },
        { leaf = "fadeLayersIn", speed = 1.79, bezier = "almostlinear" },
        { leaf = "fadeLayersOut", speed = 1.39, bezier = "almostlinear" },
        { leaf = "workspaces", speed = 1.94, bezier = "almostlinear", style = "fade" },
        { leaf = "workspacesIn", speed = 1.21, bezier = "almostlinear", style = "fade" },
        { leaf = "workspacesOut", speed = 1.94, bezier = "almostlinear", style = "fade" },
      }
      for _, animation in ipairs(animations) do
        animation.enabled = true
        hl.animation(animation)
      end

      hl.device({ name = "epic-mouse-v1", sensitivity = -0.5 })

      hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
      hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd(lock))
      hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
      hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
      hl.bind(mainMod .. " + Q", hl.dsp.window.close())
      hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exit())
      hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
      hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = 1 }))
      hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
      hl.bind(mainMod .. " + U", hl.dsp.layout("togglesplit"))

      local screenshots = {
        { mods = "", key = "PRINT", mode = "region", open = "" },
        { mods = "SHIFT", key = "PRINT", mode = "window", open = "" },
        { mods = "CTRL", key = "PRINT", mode = "active", open = "" },
        { mods = "ALT", key = "PRINT", mode = "region", open = hyprshotOpen },
        { mods = "SHIFT ALT", key = "PRINT", mode = "window", open = hyprshotOpen },
        { mods = "CTRL ALT", key = "PRINT", mode = "active", open = hyprshotOpen },
      }
      for _, screenshot in ipairs(screenshots) do
        local modifier = screenshot.mods == "" and screenshot.key or screenshot.mods:gsub(" ", " + ") .. " + " .. screenshot.key
        hl.bind(modifier, hl.dsp.exec_cmd("hyprshot -m " .. screenshot.mode .. " " .. hyprshotConf .. " " .. screenshot.open))
      end

      local directions = { h = { focus = "left", x = "-10%", y = "0" }, l = { focus = "right", x = "10%", y = "0" }, k = { focus = "up", x = "0", y = "-10%" }, j = { focus = "down", x = "0", y = "10%" } }
      for key, direction in pairs(directions) do
        hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ direction = direction.focus }))
        hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ direction = direction.focus }))
        hl.bind(mainMod .. " + ALT + " .. key, hl.dsp.window.resize({ x = tonumber(direction.x:match("%-?%d+")), y = tonumber(direction.y:match("%-?%d+")), relative = true }))
      end
      for i = 1, 10 do
        local key = i % 10
        hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
        hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
      end
      hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
      hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
      hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
      hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
      hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
      hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

      local media = {
        { key = "XF86AudioRaiseVolume", command = "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+" },
        { key = "XF86AudioLowerVolume", command = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-" },
        { key = "XF86AudioMute", command = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle" },
        { key = "XF86AudioMicMute", command = "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle" },
        { key = "XF86MonBrightnessUp", command = "brightnessctl -e4 -n2 set 5%+" },
        { key = "XF86MonBrightnessDown", command = "brightnessctl -e4 -n2 set 5%-" },
      }
      for _, binding in ipairs(media) do
        hl.bind(binding.key, hl.dsp.exec_cmd(binding.command), { locked = true, repeating = true })
      end
      for key, command in pairs({ XF86AudioNext = "playerctl next", XF86AudioPause = "playerctl play-pause", XF86AudioPlay = "playerctl play-pause", XF86AudioPrev = "playerctl previous" }) do
        hl.bind(key, hl.dsp.exec_cmd(command), { locked = true })
      end

      hl.window_rule({ name = "suppress-maximize", match = { class = ".*" }, suppress_event = "maximize" })
      hl.window_rule({ name = "no-focus-empty-xwayland", match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false }, no_focus = true })
      hl.window_rule({ name = "youtube-opacity", match = { class = "zen.*", title = ".*YouTube.*" }, opacity = 1.0 })

      hl.on("hyprland.start", function()
        hl.exec_cmd("${startScript}/bin/start")
      end)
    '';
  };
}
